name: بناء ملف APK لتطبيق Zaki AI

on:
  workflow_dispatch:  # يسمح بتشغيل العملية يدوياً من واجهة GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: تنزيل المشروع
        uses: actions/checkout@v3

      - name: إعداد JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: منح صلاحيات التنفيذ لـ Gradle
        run: chmod +x ./gradlew

      - name: بناء ملف APK
        run: ./gradlew assembleDebug

      - name: رفع ملف APK كنتيجة
        uses: actions/upload-artifact@v3
        with:
          name: zaki-ai-app
          path: app/build/outputs/apk/debug/app-debug.apk
